/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-dim": "#d9dadb",
        "on-secondary-container": "#306d58",
        "surface-variant": "#e1e3e4",
        "inverse-primary": "#4edea3",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#3e4943",
        "tertiary-fixed": "#d9e6dd",
        "on-surface-variant": "#3c4a42",
        "on-primary-fixed": "#002113",
        "background": "#f8f9fa",
        "primary-fixed-dim": "#4edea3",
        "primary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#bdcac1",
        "on-tertiary-container": "#303c36",
        "on-secondary-fixed-variant": "#0b513d",
        "surface-container-highest": "#e1e3e4",
        "secondary-container": "#adedd3",
        "primary-container": "#10b981",
        "on-error": "#ffffff",
        "outline-variant": "#bbcabf",
        "on-tertiary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "primary": "#006c49",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#f0f1f2",
        "surface-container-low": "#f3f4f5",
        "on-tertiary-fixed": "#131e19",
        "on-primary-container": "#00422b",
        "on-error-container": "#93000a",
        "surface-tint": "#006c49",
        "secondary-fixed-dim": "#95d3ba",
        "secondary-fixed": "#b0f0d6",
        "on-primary-fixed-variant": "#005236",
        "tertiary": "#55615a",
        "on-surface": "#191c1d",
        "error-container": "#ffdad6",
        "on-secondary": "#ffffff",
        "on-background": "#191c1d",
        "tertiary-container": "#99a69e",
        "secondary": "#2b6954",
        "on-secondary-fixed": "#002117",
        "surface-container-high": "#e7e8e9",
        "outline": "#6c7a71",
        "inverse-surface": "#2e3132",
        "surface": "#f8f9fa",
        "surface-bright": "#f8f9fa",
        "surface-container": "#edeeef"
      },
      fontFamily: {
        headline: ["Lexend", "sans-serif"],
        display: ["Lexend", "sans-serif"],
        body: ["Lexend", "sans-serif"],
        label: ["Lexend", "sans-serif"]
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
